name: test-conda-env-py3-macos
channels:
- conda-forge
- defaults
dependencies:
- git
- conda-forge::numpy
- conda-forge::sympy
- scipy
# https://github.com/pocl/pocl/issues/757
- pocl=1.2
- islpy
- pyopencl
- python>=3.6
- symengine=0.3.0
- python-symengine=0.3.0
- pyfmmlib
# for OpenMP support in pyfmmlib
- libgfortran>=3.0.1

- pip
- pip:
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
    - git+https://github.com/inducer/meshmode@44ed963d24b7b2f703e3b9ee9ea24bcee3cac6aa
    - git+https://gitlab.tiker.net/mattwala/boxtree@fix-cost-model-for-2d-paper-code-v2    
    - git+https://gitlab.tiker.net/mattwala/sumpy@fix-cost-model-for-2d-paper-code-v2

