name: test-conda-env-py3
channels:
- conda-forge
- defaults
dependencies:
- git
- scipy
- conda-forge::numpy
- conda-forge::sympy
- pocl
- islpy
- pyopencl
- python=3
- symengine=0.3.0
- python-symengine=0.3.0
- pyfmmlib

- pip
- pip:
    - git+https://github.com/inducer/pymbolic
    - git+https://github.com/inducer/loopy
    - git+https://github.com/inducer/meshmode    
    - git+https://gitlab.tiker.net/mattwala/boxtree@fix-cost-model-for-2d-paper-code-v2    
    - git+https://gitlab.tiker.net/mattwala/sumpy@fix-cost-model-for-2d-paper-code-v2

